# Generated by Django 5.2.7 on 2025-11-05 09:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_device_device_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('title_en', models.CharField(db_index=True, max_length=255, null=True)),
                ('title_uz', models.CharField(db_index=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('story_type', models.CharField(choices=[('PROMOTION', 'Promotion'), ('NEWS', 'News'), ('ANNOUNCEMENT', 'Announcement'), ('FEATURED', 'Featured'), ('ALL', 'All')], db_index=True, default='ALL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('duration', models.PositiveIntegerField(default=5, help_text='Duration in seconds (1-30)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('action_url', models.URLField(blank=True, help_text='External link when story is clicked', max_length=500, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'db_table': 'stories',
                'ordering': ['order', '-published_at'],
                'indexes': [models.Index(fields=['status', 'is_active'], name='story_status_active_idx'), models.Index(fields=['story_type', 'is_active'], name='story_type_active_idx'), models.Index(fields=['order', '-published_at'], name='story_order_pub_idx'), models.Index(fields=['expires_at'], name='story_expires_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_watched', models.PositiveIntegerField(default=0, help_text='How many seconds user watched (in seconds)')),
                ('completed', models.BooleanField(default=False, help_text='Whether user watched the entire story')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to='users.device')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to='story.story')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story View',
                'verbose_name_plural': 'Story Views',
                'db_table': 'story_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['story', '-viewed_at'], name='storyview_story_time_idx'), models.Index(fields=['device', '-viewed_at'], name='storyview_device_time_idx'), models.Index(fields=['user', '-viewed_at'], name='storyview_user_time_idx')],
                'unique_together': {('story', 'device', 'user')},
            },
        ),
    ]
