# Generated by Django 5.2.7 on 2025-11-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'Phone'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('gmail', 'Gmail')], max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='contact_icons/')),
            ],
        ),
    ]
